# Generated by Django 3.2.5 on 2021-08-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210803_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(choices=[('P', 'Pets'), ('D', 'Dance'), ('F', 'Fun')], default='F', max_length=200),
        ),
    ]
