# Generated by Django 3.2.5 on 2021-07-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.URLField(default='http://images4.fanpop.com/image/photos/15800000/Cupcakes-random-15805648-480-493.jpg'),
        ),
    ]
